### ISSUE TITLE
ERROR: .ext/rdoc already exists, but it looks like it isn't an RDoc directory.

### ISSUE THREAD

**Issue by gregorskii** [Stouts/Stouts.ruby#1]
HI there,

This task is failing for me when installing Ruby on Ubuntu 14.04 Trusty.

```
Directory .ext/rdoc already exists, but it looks like it isn't an RDoc directory.

Because RDoc doesn't want to risk destroying any of your existing files,
you'll need to specify a different output directory name (using the --op <dir>
option)

/usr/local/src/ruby-2.1.2/lib/rdoc/rdoc.rb:108:in `error'
    /usr/local/src/ruby-2.1.2/lib/rdoc/rdoc.rb:208:in `rescue in setup_output_dir'
    /usr/local/src/ruby-2.1.2/lib/rdoc/rdoc.rb:195:in `setup_output_dir'
    /usr/local/src/ruby-2.1.2/lib/rdoc/rdoc.rb:475:in `document'
    ./bin/rdoc:20:in `<main>'

```

```

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/User/site.retry

master                     : ok=36   changed=5    unreachable=0    failed=0
slave                      : ok=36   changed=5    unreachable=0    failed=0
stage1                     : ok=79   changed=11   unreachable=0    failed=1
stagedb                    : ok=35   changed=5    unreachable=0    failed=0
web1                       : ok=63   changed=8    unreachable=0    failed=0
web2                       : ok=63   changed=8    unreachable=0    failed=0

```

**Comment by obelich** [comment]
I confirm that error i get the same error trying to compile  Ruby 2.2.3

**Comment by khusnetdinov** [comment]
- 1
  2.2.0 Trusty
